#服务名称 端口
server:
  port: 9090
spring:
  application:
    name: gateway-server
  cloud:
    nacos:  # nacos url
      discovery:
        server-addr: localhost:8848
    sentinel: #sentinel url
      transport:
        dashboard: localhost:8080
    gateway:   # gateway
      discovery:
        locator:
          enabled: true #开启gateway从nacos上获取服务列表

feign:
  sentinel:
    enabled: true